const VARCHAR_TYPE = {
    FIRST_NAME: 'FIRST_NAME', 
    LAST_NAME: 'LAST_NAME',
    FULL_NAME: 'FULL_NAME',
    ADDRESS: 'ADDRESS',
    COMPANY: 'COMPANY',
    ID_NUMBER: 'ID_NUMBER',
    PHONE_NUMBER: 'PHONE_NUMBER'
}

export default VARCHAR_TYPE;